# Generated by Django 5.2.12 on 2026-04-06 23:54

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Actor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('birth_date', models.DateField(blank=True, null=True)),
                ('nationality', models.CharField(blank=True, choices=[('USA', 'American'), ('ENGLAND', 'British'), ('CANADA', 'Canadian'), ('FRANCE', 'French'), ('GERMANY', 'German'), ('INDIA', 'Indian'), ('JAPAN', 'Japanese'), ('BRAZIL', 'Brazilian'), ('CHINA', 'Chinese'), ('ITALY', 'Italian'), ('SPAIN', 'Spanish'), ('RUSSIA', 'Russian'), ('MEXICO', 'Mexican'), ('KOREA', 'Korean'), ('AUSTRALIA', 'Australian'), ('AFRICA', 'African'), ('ARGENTINA', 'Argentinian'), ('OTHER', 'Other')], max_length=100, null=True)),
            ],
        ),
    ]
